apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: default
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: frontend-peer-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gateway-peer-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: api-gateway
  mtls:
    mode: STRICT